// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GDToolTips
{
    internal sealed partial class Vsix
    {
        public const string Id = "GDToolTips.23d41193-c3c9-4455-9269-e986a57bfdac";
        public const string Name = "GDToolTips";
        public const string Description = @"Add author name to file";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "ReinGD";
        public const string Tags = "";
    }
}
