// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GDToolTips
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GDToolTipsString = "5c591198-ef21-45ea-b67c-4a503a3b6614";
        public static Guid GDToolTips = new Guid(GDToolTipsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GDMenuGroup = 0x0001;
        public const int Signature = 0x0100;
    }
}